version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - codecov/upload
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn clean test

workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
