
version: 2.1
orbs: 

jobs:

  build-and-test:
  
    docker:
      - image: cimg/openjdk:11.0
    
    steps:
      
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      
      - run:
          name: Test
          command: mvn test
workflows:
   sample: 
    jobs:
      - build-and-test
      

